//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AI_NavMeshPathStatusWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.AI.NavMeshPathStatus));
		L.RegVar("PathComplete", get_PathComplete, null);
		L.RegVar("PathPartial", get_PathPartial, null);
		L.RegVar("PathInvalid", get_PathInvalid, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.AI.NavMeshPathStatus>.Check = CheckType;
		StackTraits<UnityEngine.AI.NavMeshPathStatus>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.AI.NavMeshPathStatus arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.AI.NavMeshPathStatus), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PathComplete(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AI.NavMeshPathStatus.PathComplete);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PathPartial(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AI.NavMeshPathStatus.PathPartial);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PathInvalid(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AI.NavMeshPathStatus.PathInvalid);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.AI.NavMeshPathStatus o = (UnityEngine.AI.NavMeshPathStatus)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

